/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author funghu
 */
public class CanteenGoodsManagementFrame extends javax.swing.JFrame {
    Connection conn;
    private javax.swing.JTable table;
    
    Vector<Vector<Object>> data = new Vector<Vector<Object>>();
    /**
     * Creates new form CanteenGoodsManagementFrame
     */
    public CanteenGoodsManagementFrame() {
        initComponents();
        this.table = new javax.swing.JTable();
        initializeDatabaseConnection();
        loadDataFromDatabase();
        populateTable();
        TableScrollPane.setViewportView(table); 
    }
    
    private void initializeDatabaseConnection() {
        try {
            conn = new JDBCPostgreSQLConnection().connect();
        } catch (Exception e) {
            Logger.getLogger(CanteenPurchaseFrame.class.getName()).log(Level.SEVERE, "Database connection failed", e);
        }
    }

    private void loadDataFromDatabase() {
        data = new Vector<>();
        try (Statement stmt = conn.createStatement();
           ResultSet rs = stmt.executeQuery("SELECT * FROM public.canteen_product")) {
            while (rs.next()) {
                Vector<Object> row = new Vector<>();
                row.add(rs.getString("ProductName"));
                row.add(rs.getDouble("Price")); // Directly add the price as Double
                row.add(0); // Count
                data.add(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CanteenPurchaseFrame.class.getName()).log(Level.SEVERE, "Failed to load data", ex);
        }
    }
    private void populateTable() {
        if (data.isEmpty()) {
            Logger.getLogger(CanteenPurchaseFrame.class.getName()).log(Level.WARNING, "No data to display");
            return;
        }

        Object[][] tableData = convertDataToTableFormat();
        DefaultTableModel tableModel = createTableModel(tableData);

        table.setModel(tableModel);
        tableModel.fireTableDataChanged();
        
        tableModel.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                if (e.getType() == TableModelEvent.UPDATE && e.getColumn() == 2) {
                    updateTotalPrice();
                }
            }
        });
        
    }
    
     /**
     * Converts the Vector data into a 2D Object array for the table model.
     */
    private Object[][] convertDataToTableFormat() {
        int rowCount = data.size();
        int colCount = data.get(0).size();
        Object[][] tableData = new Object[rowCount][colCount];

        for (int i = 0; i < rowCount; i++) {
            for (int j = 0; j < colCount; j++) {
                tableData[i][j] = data.get(i).get(j);
//                System.out.println(tableData[i][j]);
            }
        }

        return tableData;
    }
    
    private DefaultTableModel createTableModel(Object[][] tableData) {
        // Exclude the checkbox column
       return new DefaultTableModel(tableData, new Object[]{"Product Name", "Price", "Count"}) {
           @Override
           public Class<?> getColumnClass(int columnIndex) {
               return switch (columnIndex) {
                   case 1 -> Double.class;
                   case 2 -> Integer.class;
                   default -> String.class;
               }; 
           }

           @Override
           public boolean isCellEditable(int row, int column) {
               return column == 2; // Make count column editable
           }
           
           
       };
    }
    
    private void updateAVGPrice() {
        double totalPrice = 0;
        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
        for (int row = 0; row < tableModel.getRowCount(); row++) {
            double price = (double) tableModel.getValueAt(row, 1);
            int count = (int) tableModel.getValueAt(row, 2);
            totalPrice += price * count;
        }
        TotalPriceLabel.setText("Total: " + totalPrice + " tl");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopPanel = new javax.swing.JPanel();
        CenterPanel = new javax.swing.JPanel();
        TableScrollPane = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BottomPanel = new javax.swing.JPanel();
        ProductName = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(90, 0), new java.awt.Dimension(32767, 0));
        SubmitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(TopPanel, java.awt.BorderLayout.PAGE_START);

        CenterPanel.setLayout(new javax.swing.BoxLayout(CenterPanel, javax.swing.BoxLayout.LINE_AXIS));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableScrollPane.setViewportView(jTable1);

        CenterPanel.add(TableScrollPane);

        getContentPane().add(CenterPanel, java.awt.BorderLayout.CENTER);

        BottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        ProductName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ProductName.setText("ProductName");
        BottomPanel.add(ProductName);

        Price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Price.setText("Price");
        BottomPanel.add(Price);
        BottomPanel.add(filler1);

        SubmitButton.setText("Submit");
        BottomPanel.add(SubmitButton);

        getContentPane().add(BottomPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CanteenGoodsManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CanteenGoodsManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CanteenGoodsManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CanteenGoodsManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CanteenGoodsManagementFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField ProductName;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JScrollPane TableScrollPane;
    private javax.swing.JPanel TopPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
